### ISSUE TITLE
I'm attempting to update this to ffmpeg 2.1...

### ISSUE THREAD

**Issue by Wowfunhappy** [RJVB/FFusion#1]
Hello! I'm trying to get this working with at least ffmpeg 2.1 (the first version of ffmpeg to support hevc and vp9), and I was wondering if you might be willing to offer a bit of guidance.

I've gotten [my fork](https://github.com/wowfunhappy/FFusion) to build successfully on OS X 10.9 and Xcode 5.0.2, and I _think_ I'm actually super close to having working playback! You see, if I modify the function `parse_mpeg4_stream` to always return zero, I'm able to see a few seconds of my video in QuickTime, albeit with the frames clearly showing up out of order:

https://user-images.githubusercontent.com/4484096/103667449-f2cf3100-4f43-11eb-85fb-2eae81eba187.mov

Unfortunately, if I allow the function to run through, FFusion crashes on this line: https://github.com/Wowfunhappy/FFusion/blob/68edcdd619ae95dd31789e4acbda52c47cd869ea/bitstream_info.c#L236

```
s->avctx = parser->avctx;
```

`s` is an MpegEncContext struct (declared within ffmpeg's sources), and `parser` is a FFusionParserContext struct that gets passed into the function. Both contain an AVCodecContext field `avctx`, and since assignment is failing, I'm inclined to think `parser`'s avctx isn't getting initialized somehow.

To that end, I noticed something odd near the end of `ffusionParserInit`: https://github.com/Wowfunhappy/FFusion/blob/68edcdd619ae95dd31789e4acbda52c47cd869ea/bitstream_info.c#L1001

```
	parserContext->parserStructure = ffParser;
	if(ffParser->internalContextSize) {
		parserContext->internalContext = av_mallocz(ffParser->internalContextSize);
	}
	else {
		//This seems relevent?
		asl_log(NULL, NULL, ASL_LEVEL_ERR, "Wha?");
		parserContext->internalContext = NULL;
	}
	if(ffParser->init)
		(ffParser->init)(parserContext);
    return parserContext;
```

It looks like the check for `ffParser->internalContextSize` is always returning false ("Wha?" gets logged), and consequently setting `parserContext->internalContext` to `NULL`. Although for all I know, this is expected.

I'm feeling a little bit stuck at this point, because I don't really know what I'm doing and _definitely_ don't understand the internals of ffmpeg.  I don't know if it will help, but if you could offer any guidance as to what might be going on, I'd appreciate it! It's just killing me that it seems to be so close to working!

Thank you!

**Comment by RJVB** [comment]
On Tuesday January 05 2021 08:20:55 Jonathan wrote:

Hi!

Courageous man! I haven't touched this code, well, since the date of the last commit in my repo I suppose, and certainly cannot remember much about it. In part that is because the code isn't mine, and I only ever understood it as far as necessary to strip it out of Perian and get it to build on MSWin...

>Unfortunately, if I allow the function to run through, FFusion crashes on this line: https://github.com/Wowfunhappy/FFusion/blob/68edcdd619ae95dd31789e4acbda52c47cd869ea/bitstream_info.c#L236
>
>```
>s->avctx = parser->avctx;
>```
>
>`s` is an MpegEncContext struct (declared within ffmpeg's sources), and `parser` is a FFusionParserContext struct that gets passed into the function. Both contain an AVCodecContext field `avctx`, and since assignment is failing, I'm inclined to think `parser`'s avctx isn't getting initialized somehow.

No, assuming that `s` was allocated appropriately the most likely reason is that `parser` itself is not initialised, or got corrupted. If frames end up out of order I would lean towards the 2nd explanation though the disorder could also be itself the result of the use of something not properly initialised. You could try launching your player through vgrind. Or just attach a debugger, set a breakpoint on the line above and check the contents of both `s` and `parser` before executing the statement.

>It looks like the check for `ffParser->internalContextSize` is always returning false ("Wha?" gets logged), and consequently setting `parserContext->internalContext` to `NULL`. Although for all I know, this is expected.

I have no idea, but I cannot find any indication that `internalContextSize` is ever set (not even to 0!). I *presume* this controls a buffer for internal context that was never implemented ... OR it's something that ffmpeg uses or might use.

>I'm feeling a little bit stuck at this point, because I don't really know what I'm doing and _definitely_ don't understand the internals of ffmpeg.

It's been ages for me too. The best I can suggest is to subscribe to the FFMpeg mailing list and raise your issue there. They've always been helpful to me in the past. But first and if you can, extract the FFmpeg code into a small command line utility that prints some info about each extracted frame so you can check what gets fed into QuickTime. That will make your porting process quicker (at least the "getting things to work" bit) and it'll make it easier to discuss your issue(s) with the FFmpeg devs.

BTW, the Perian code (which is where I got FFusion from; they in turn embedded it from an older project) is now on github: @gbooker/perian . It seems they managed to preserve the SVN commit history when they imported the code, so the `blame` feature works and can help you learn a bit more about bits of code that are not self-explanatory or commented otherwise.

Good luck!
R.

>I don't know if it will help, but if you could offer any guidance as to what might be going on, I'd appreciate it! It's just killing me that it seems to be so close to working!
>
>Thank you!
>
>

**Comment by Wowfunhappy** [comment]
Thank you! Helpful to read!
